export const facultyData = [
  {
    id: 1,
    name: "Dr. K. K. Sharma",
    designation: "Executive Secretary",
    image: "/images/home-page/seven-dummy-img.png",
    link: "#",
    school: "Engineering",
    type: "Full-Time",
    // Additional fields for detail page (to be replaced with API data)
    profile:
      "Dr Apurva is an Assistant Professor in the area of Business Communication at IIM Jammu. He received his doctoral degree in Linguistics from IIT Delhi, Dept of Humanities and Social Sciences...",
    email: "kksharma@university.edu",
    linkedin: "https://linkedin.com/in/kksharma",
    education: [
      "Certification on Leadership Development, IIM – Ahmedabad (2023)",
      "ET611Tx: Pedagogy for effective use of ICT for school teachers, IIT Bombay (2017)",
      "PGDM (Insurance), Birla Institute of Management Technology (2012)",
      "B.com, Lucknow University (2010)",
    ],
    research: {
      googleScholar: "#",
      orcid: "#",
      researchGate: "#",
      scopus: "#",
      vidwan: "#",
    },
    teaching: [
      "Business communication",
      "Technical English",
      "English Language",
      "English Language phase B",
    ],
    awards: [
      "Outstanding Educator Award – Recognized for excellence in teaching and curriculum development in Business Communication.",
      "Best Paper Presentation at International Conference – Awarded for pioneering research on corporate communication trends.",
    ],
    socialEngagement: [
      "Outstanding Educator Award – Recognized for excellence in teaching.",
      "Best Paper Presentation at International Conference.",
    ],
  },
  {
    id: 2,
    name: "Dr. R. K. Agarwal",
    designation: "Executive Secretary",
    image: "/images/home-page/seven-dummy-img.png",
    link: "#",
    school: "Computing",
    type: "Visiting",
    profile:
      "Dr R. K. Agarwal is a renowned professor in the field of Computer Science...",
    email: "rkagarwal@university.edu",
    linkedin: "https://linkedin.com/in/rkagarwal",
    education: [
      "Ph.D. in Computer Science, IIT Delhi (2015)",
      "M.Tech in Software Engineering, IIT Bombay (2010)",
      "B.Tech in Computer Science, NIT Kurukshetra (2008)",
    ],
    research: {
      googleScholar: "#",
      orcid: "#",
      researchGate: "#",
      scopus: "#",
      vidwan: "#",
    },
    teaching: [
      "Data Structures and Algorithms",
      "Machine Learning",
      "Artificial Intelligence",
      "Cloud Computing",
    ],
    awards: ["Best Teacher Award 2023", "Excellence in Research Award 2022"],
    socialEngagement: [
      "Mentor for coding bootcamps",
      "Guest speaker at tech conferences",
    ],
  },
  {
    id: 3,
    name: "Dr. S. K. Verma",
    designation: "Executive Secretary",
    image: "/images/home-page/seven-dummy-img.png",
    link: "#",
    school: "Architecture",
    type: "Full-Time",
    profile:
      "Dr S. K. Verma specializes in sustainable architecture and urban planning...",
    email: "skverma@university.edu",
    linkedin: "https://linkedin.com/in/skverma",
    education: [
      "Ph.D. in Architecture, SPA Delhi (2016)",
      "M.Arch in Urban Design, CEPT Ahmedabad (2012)",
      "B.Arch, School of Planning and Architecture (2010)",
    ],
    research: {
      googleScholar: "#",
      orcid: "#",
      researchGate: "#",
      scopus: "#",
      vidwan: "#",
    },
    teaching: [
      "Sustainable Architecture",
      "Urban Planning",
      "Architectural Design",
      "Building Technology",
    ],
    awards: [
      "Best Architecture Design Award 2023",
      "Sustainability Excellence Award 2021",
    ],
    socialEngagement: [
      "Community planning initiatives",
      "Green building advocacy",
    ],
  },
  {
    id: 4,
    name: "Dr. K. K. Sharma",
    designation: "Executive Secretary",
    image: "/images/home-page/seven-dummy-img.png",
    link: "#",
    school: "Engineering",
    type: "Full-Time",
    profile: "Dr Apurva is an Assistant Professor...",
    email: "kksharma2@university.edu",
    linkedin: "https://linkedin.com/in/kksharma2",
    education: ["Ph.D. in Engineering", "M.Tech in Mechanical Engineering"],
    research: {
      googleScholar: "#",
      orcid: "#",
      researchGate: "#",
      scopus: "#",
      vidwan: "#",
    },
    teaching: ["Thermodynamics", "Fluid Mechanics"],
    awards: ["Teaching Excellence Award"],
    socialEngagement: ["Industry collaboration programs"],
  },
  {
    id: 5,
    name: "Dr. R. K. Agarwal",
    designation: "Executive Secretary",
    image: "/images/home-page/seven-dummy-img.png",
    link: "#",
    school: "Computing",
    type: "Visiting",
    profile: "Dr R. K. Agarwal is a renowned professor...",
    email: "rkagarwal2@university.edu",
    linkedin: "https://linkedin.com/in/rkagarwal2",
    education: ["Ph.D. in Computer Science"],
    research: {
      googleScholar: "#",
      orcid: "#",
      researchGate: "#",
      scopus: "#",
      vidwan: "#",
    },
    teaching: ["Database Management", "Web Technologies"],
    awards: ["Research Excellence Award"],
    socialEngagement: ["Tech workshops"],
  },
  {
    id: 6,
    name: "Dr. S. K. Verma",
    designation: "Executive Secretary",
    image: "/images/home-page/seven-dummy-img.png",
    link: "#",
    school: "Architecture",
    type: "Full-Time",
    profile: "Dr S. K. Verma specializes in sustainable architecture...",
    email: "skverma2@university.edu",
    linkedin: "https://linkedin.com/in/skverma2",
    education: ["Ph.D. in Architecture"],
    research: {
      googleScholar: "#",
      orcid: "#",
      researchGate: "#",
      scopus: "#",
      vidwan: "#",
    },
    teaching: ["Architectural Theory"],
    awards: ["Design Innovation Award"],
    socialEngagement: ["Urban design projects"],
  },
  {
    id: 7,
    name: "Dr. P. K. Verma",
    designation: "Executive Secretary",
    image: "/images/home-page/seven-dummy-img.png",
    link: "#",
    school: "Architecture",
    type: "Full-Time",
    profile: "Dr P. K. Verma is an expert in construction management...",
    email: "pkverma@university.edu",
    linkedin: "https://linkedin.com/in/pkverma",
    education: ["Ph.D. in Construction Management"],
    research: {
      googleScholar: "#",
      orcid: "#",
      researchGate: "#",
      scopus: "#",
      vidwan: "#",
    },
    teaching: ["Construction Management"],
    awards: ["Project Management Excellence"],
    socialEngagement: ["Construction industry collaboration"],
  },
  {
    id: 8,
    name: "Dr. N. K. Kohli",
    designation: "Executive Secretary",
    image: "/images/home-page/seven-dummy-img.png",
    link: "#",
    school: "Architecture",
    type: "Full-Time",
    profile: "Dr N. K. Kohli focuses on heritage conservation...",
    email: "nkkohli@university.edu",
    linkedin: "https://linkedin.com/in/nkkohli",
    education: ["Ph.D. in Heritage Conservation"],
    research: {
      googleScholar: "#",
      orcid: "#",
      researchGate: "#",
      scopus: "#",
      vidwan: "#",
    },
    teaching: ["Heritage Conservation"],
    awards: ["Conservation Excellence Award"],
    socialEngagement: ["Heritage restoration projects"],
  },
];
